"""empty message

Revision ID: 4c4e369ab8aa
Revises: 
Create Date: 2024-07-04 23:51:28.169258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4e369ab8aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('diamonds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=150), nullable=True))
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=True))
        batch_op.drop_column('wallet_address')
        batch_op.drop_column('diamonds')
        batch_op.drop_column('coins')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
